stages:
  - install
  - sonar
  - report   

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

cache:
  paths:
    - node_modules/
    - .sonar/cache

install_dependencies:
  stage: install
  image: node:20
  tags:
    - local-sast
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

sonar_scan:
  stage: sonar
  image: sonarsource/sonar-scanner-cli:latest
  tags:
    - local-sast
  script:
    - sonar-scanner
      -Dsonar.projectKey=SonarSASTNodeAngular
      -Dsonar.sources=.
      -Dsonar.host.url=http://192.168.204.29:9000
      -Dsonar.login=$SONAR_TOKEN
  only:
    - main
    - develop

sonar_to_gitlab_sast:
  stage: report   # 
  image: node:20
  tags:
    - local-sast
  needs:
    - job: sonar_scan   # 
  script:
    # instalar curl por si acaso
    - apt-get update && apt-get install -y curl

    # esperar a que Sonar procese resultados (MUY IMPORTANTE)
    - echo "Esperando análisis de SonarQube..."
    - sleep 10

    # obtener vulnerabilidades
    - "curl -u $SONAR_TOKEN: http://192.168.204.29:9000/api/issues/search?types=VULNERABILITY&ps=500 -o sonar-issues.json"

    # convertir
    - node convert-to-gitlab-sast.js sonar-issues.json gl-sast-report.json
  artifacts:
    reports:
      sast: gl-sast-report.json
    paths:
      - gl-sast-report.json
  only:
    - main
    - develop